
envName: null
profile: null

# if set, override all Applications to use this project
projectOverride: null


default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    # destinations: |
    #   - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
    #     server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    enableAutoSync: null
    autoSyncPrune: true
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: null
      repoURL: null
      targetRevision: HEAD

      # extraSourceFields: |
      #   helm:
      #     valueFiles:
      #     - values.yaml
      #     - values-base.yaml          
      #     - values-{{ $.Values.profile }}-{{ $.Values.envName }}.yaml

projects:

  cert-manager:
    description: 'cert manager deployment'
    sourceRepos:
    - git@github.com:paas2/cert-manager.git
    destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc  
    - namespace: kube-system
      server: https://kubernetes.default.svc  

    # extraFields: |
    #   clusterResourceWhitelist:
    #   - group: '*'
    #     kind: '*'                       

applications:
  cert-manager:
    enabled: false
    destination:
      namespace: null
      server: null
    project: cert-manager
    source:
      path: helm-charts/cert-manager
      repoURL: git@github.com:paas2/cert-manager.git   
      # # apps can override the default extraSourceFields
      # #
      # extraSourceFields: |
      #   helm:
      #     valueFiles:
      #     - my-app-overrides-{{ $.Values.envName }}-values.yaml
      #     - {{ $.Values.envName }}-values.yaml               